### PR TITLE
Fixed access level Swift 4.1 build errors

### LINKED ISSUE #28: is inaccessible due to 'private' protection level error
I'm running an IOS 9.2 application which includes DynamicBlurView.  It had been running without error and I just incurred 18 DynamicBlurView errors which states, "is inaccessible due to 'private' protection level error".  How should I correct this issue.

### PR DESCRIPTION
**Pull request by kuchmiyalex**
Fixed #28

### CODE REVIEW

**Comment by KyoheiG3** [comment]
Refs #33

**Comment by stonekase** [comment]
I am still having this problem

**Comment by KyoheiG3** [comment]
Did you reference #33 ?

**Comment by stonekase** [comment]
screen shot 2018-09-28 at 12 38 08 pm

**Pull request closed without merging**
