### PR TITLE
Swift 4.2 compatibility

### PR DESCRIPTION
**Pull request by mwfire**
As of the upcoming official Swift 4.2 release, this PR incorporates the changes needed to support 4.2.
Before the official release, I would recommend to merge this PR to a dedicated Swift 4.2 branch, which I am not able to do :)

I did not bump version, though, as I think you have a better understanding on how you want to version DynamicBlurView.

Hope that makes sense :)

### CODE REVIEW

**Comment by mwfire** [comment]
Hey @KyoheiG3,

just wanted to bump this. Is there a chance this will be merged anytime soon? My library https://github.com/Orderella/PopupDialog depends on it and I would love to keep it updated. If you are not maintaining this library anymore, please give me shout.

Thanks, mate!

**Comment by electic** [comment]
Hi. I am using this library as well. It would be fantastic if this could all be merged.

**Comment by KyoheiG3** [comment]
Hi @mwfire 
Thank you for your awesome PR!!

**Comment by pushchris** [comment]
@KyoheiG3 could we get the Podspec version updated so the latest can be pulled? Thanks!

**Comment by KyoheiG3** [comment]
@pushchris I updated just now.
Thanks.

**Comment by mwfire** [comment]
Thanks a lot @KyoheiG3!  🎉🎉🎉

**Pull request merged**
